{
  "videos": [
             { "id": 1, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vid.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 2, "name": "自动录播教室使用管理规定自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi01.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 3, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi02.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 4, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi03.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 5, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi01.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 6, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi02.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 7, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi03.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 8, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi01.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 9, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi02.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 10, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi03.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" },
             { "id": 11, "name": "自动录播教室使用管理规定", "author": "张三", "description": "造成这样问题主要是因为视频界面采用的显示模式不同于普通的画面显示，它是采用的一种叫做YUY2的覆盖显示模式，当采用这种模式的用这种模式的用这种模式的用这种模式的用这种模式的用这时候……", "second": "15分钟", "imageFileName": "${b.static_url('video','images/vi01.png')}", "fileName": "${b.static_url('video','images/bfq.png')}", "publishedAt": "2017-10-25" }
            ]
}
